### ISSUE TITLE
Issue running on localhost

### ISSUE THREAD

**Issue by cesariomartins** [torusresearch/w3a-mpc-demo#4]
I am following this [guide](https://web3auth.io/docs/guides/mpc) and getting the error below when using "Get accounts" from the demo. 
[
"ETH Address: {\n \"code\": -32603,\n \"message\": \"Failed to fetch\",\n \"data\": {\n \"originalError\": {}\n },\n \"stack\": \"Error: Failed to fetch\\n at getEthJsonRpcError (http://localhost:3000/static/js/bundle.js:90673:10)\\n at Object.internal (http://localhost:3000/static/js/bundle.js:90559:22)\\n at provider.sendAsync (http://localhost:3000/static/js/bundle.js:19760:71)\\n at async provider.request (http://localhost:3000/static/js/bundle.js:19788:17)\"\n}"
]

<img width="1552" alt="captura_de_tela_2022-12-12_a__s_16 06 28" src="https://user-images.githubusercontent.com/8283313/207144573-a9279765-81a9-43a1-aa78-7df78d370939.png">

Please advise on what to do.

**Comment by derekchiang** [comment]
Can confirm that I'm running into the same issue.
